mp_project/mediaportalapp/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LogoutView
from mediaportalapp.views import CategoryListView, CategoryDetailView, ArticleDetailView, DynamicArticleImageView, CreateCommentView, DisplayArticlesByCategoryView, UserReactionView, RegistrationView, LoginView, UserAccountView, AddArticleToFavorites, RemoveArticleFromFavorites, SearchView

urlpatterns = [
    path('', CategoryListView.as_view(), name='base_view'),
    path('category/<slug>', CategoryDetailView.as_view(), name='category_detail'),
    path('<category>/<slug>', ArticleDetailView.as_view(), name='article_detail'),
    path('show_article_image', DynamicArticleImageView.as_view(), name='article_image'),
    path('add_comment/', CreateCommentView.as_view(), name='add_comment'),
    path('display_articles_by_category', DisplayArticlesByCategoryView.as_view(), name='articles_by_category'),
    path('user_reaction/', UserReactionView.as_view(), name='user_reaction'),
    path('login/', LoginView.as_view(), name='login'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('user_account/<user>/', UserAccountView.as_view(), name='account_view'),
    path('add_to_fav/', AddArticleToFavorites.as_view(), name='add_to_fav'),
    path('remove_from_fav/', RemoveArticleFromFavorites.as_view(), name='remove_from_fav'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('base_view')), name='logout'),
    path('search/', SearchView.as_view(), name='search')
]

mp_project/mp_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mediaportalapp.urls'))
]
 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mp_project/mediaportalapp/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation

class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})

def generate_filename(instance, filename):
    filename = instance.slug + '.jpg'
    return '{0}/{1}'.format(instance.slug, filename)

class ArticleManager(models.Manager):
    def all(self, *args, **kwargs):
        return super(ArticleManager, self).get_queryset().filter(pk__in=[1, 3, 5])

class Article(models.Model):
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE
    )
    title = models.CharField(max_length=120)
    slug = models.SlugField()
    image = models.ImageField(upload_to=generate_filename)
    content = models.TextField()
    likes = models.PositiveIntegerField(default=0)
    dislikes = models.PositiveIntegerField(default=0)
    comments = GenericRelation('comments')
    users_reaction = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)

    def __str__(self):
        return "Статья '{0}' из категории '{1}'".format(self.title, self.category.name)

    def get_absolute_url(self):
        return reverse('article_detail', kwargs={'category': self.category.slug, 'slug': self.slug})

class Comments(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    comment = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE
    )
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

class UserAccount(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE
    )
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    fav_articles = models.ManyToManyField(Article, blank=True)
    
    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('account_view', kwargs={'user': self.user.username})

mp_project/mediaportalapp/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class CommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea)
    
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['comment'].label = 'Комментарий'


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError('Пользователь с таким логином не найден!')
        user = User.objects.get(username=username)
        if not user.check_password(password):
            raise forms.ValidationError('Неправильный пароль!')

class RegistrationForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)
    password_check = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'username',
            'password',
            'password_check',
            'first_name',
            'last_name',
            'email'
        ]
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['username'].help_text = 'Обязательное поле'
        self.fields['password'].label = 'Пароль'
        self.fields['password_check'].label = 'Подтвердите пароль'
        self.fields['first_name'].label = 'Имя'
        self.fields['last_name'].label = 'Фамилия'
        self.fields['email'].label = 'Ваш E-mail'

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        password_check = self.cleaned_data['password_check']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Пользователь с таким именем уже существует!')
        if password != password_check:
            raise forms.ValidationError('Пароли не совпадают!')

mp_project/mediaportalapp/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from mediaportalapp.models import Article, Category, UserAccount
from django.db.models import Q
from mediaportalapp.mixins import CategoryAndArticlesListMixin
from django.http import JsonResponse, HttpResponseRedirect
from django.views import View
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib.auth.models import AnonymousUser
from mediaportalapp.forms import CommentForm, RegistrationForm, LoginForm

User = get_user_model()

class ArticleListView(ListView):
    model = Article
    template_name = 'index.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ArticleListView, self).get_context_data(*args, **kwargs)
        context['articles'] = self.model.objects.all()
        return context

class CategoryListView(ListView, CategoryAndArticlesListMixin):
    model = Category
    template_name = 'index.html'

    def get_context_data(self, *args, **kwargs):
        context = super(CategoryListView, self).get_context_data(*args, **kwargs)
        context['categories'] = self.model.objects.all()
        context['articles'] = Article.objects.all()[:4]
        context['slider_articles'] = Article.objects.order_by('?')[:3]
        context['article'] = Article.objects.get(id=1)
        return context

class CategoryDetailView(DetailView, CategoryAndArticlesListMixin):
    model = Category
    template_name = 'category_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(*args, **kwargs)
        context['category'] = self.get_object()
        context['articles_from_category'] = self.get_object().article_set.all()
        return context

class ArticleDetailView(DetailView, CategoryAndArticlesListMixin):
    model = Article
    template_name = 'article_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(*args, **kwargs)
        context['article'] = self.get_object()
        context['article_comments'] = self.get_object().comments.all()
        context['form'] = CommentForm()
        if self.request.user.is_authenticated:
            context['current_user'] = UserAccount.objects.get(user=self.request.user)
        else:
            context['current_user'] = AnonymousUser
        return context

class DynamicArticleImageView(View):
    def get(self, request, *args, **kwargs):
        article_id = self.request.GET.get('article_id')
        article = Article.objects.get(id=article_id)
        data = {
            'article_image': article.image.url
        }
        return JsonResponse(data)

class CreateCommentView(View):
    template_name: 'article_detail.html'

    def post(self, request, *args, **kwargs):
        article_id = self.request.POST.get('article_id')
        comment = self.request.POST.get('comment')
        article = Article.objects.get(id=article_id)
        new_comment = article.comments.create(author=request.user, comment=comment)
        comment = [{ 'author': new_comment.author.username, 'comment': new_comment.comment, 'timestamp': new_comment.timestamp.strftime('%Y-%m-%d') }]
        return JsonResponse(comment, safe=False)

class DisplayArticlesByCategoryView(View):
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        category_slug = self.request.GET.get('category_slug')
        articles = list(Article.objects.filter(category=Category.objects.get(slug = category_slug)).values('title', 'image', 'slug'))
        data = {
            'articles': articles
        }
        return JsonResponse(data)

class UserReactionView(View):
    template_name = 'article_detail.html'

    def get(self, request, *args, **kwargs):
        article_id = self.request.GET.get('article_id')
        article = Article.objects.get(id=article_id)
        like = self.request.GET.get('like')
        dislike = self.request.GET.get('dislike')
        if like and (request.user not in article.users_reaction.all()):
            article.likes += 1
            article.users_reaction.add(request.user)
            article.save()
        if dislike and (request.user not in article.users_reaction.all()):
            article.dislikes += 1
            article.users_reaction.add(request.user)
            article.save()
        data = {
            'likes': article.likes,
            'dislikes': article.dislikes
        }
        return JsonResponse(data)

class RegistrationView(View):
    template_name = 'registration.html'

    def get(self, request, *args, **kwargs):
        form = RegistrationForm()
        categories = Category.objects.all()
        context = {
            'form': form,
            'categories': categories
        }
        return render(self.request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = RegistrationForm(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            new_user.set_password(password)
            password_check = form.cleaned_data['password_check']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            new_user.save()
            UserAccount.objects.create(user=User.objects.get(username=new_user.username),
                                                            first_name=new_user.first_name,
                                                            last_name=new_user.last_name,
                                                            email=new_user.email)
            return HttpResponseRedirect('/')
        context = {
            'form': form
        }
        return render(self.request, self.template_name, context)

class LoginView(View):
    template_name = 'login.html'

    def get(self, request, *args, **kwargs):
        form = LoginForm()
        categories = Category.objects.all()
        context = {
            'form': form,
            'categories': categories
        }
        return render(self.request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(self.request, user)
                return HttpResponseRedirect('/')
        context = {
            'form': form
        }
        return render(self.request, self.template_name, context)

class UserAccountView(View, CategoryAndArticlesListMixin):
    template_name = 'user_account.html'

    def get(self, request, *args, **kwargs):
        user = self.kwargs.get('user')
        categories = Category.objects.all()
        current_user = UserAccount.objects.get(user=User.objects.get(username=user))
        context = {
            'current_user': current_user,
            'categories': categories
        }
        return render(self.request, self.template_name, context)

class AddArticleToFavorites(View):
    template_name = 'article_detail.html'

    def get(self, request, *args, **kwargs):
        article_slug = self.request.GET.get('article_slug')
        article = Article.objects.get(slug=article_slug)
        current_user = UserAccount.objects.get(user=request.user)
        current_user.fav_articles.add(article)
        current_user.save()
        return JsonResponse({ 'ok':'ok' })

class RemoveArticleFromFavorites(View):
    template_name = 'user_account.html'

    def get(self, request, *args, **kwargs):
        article_slug = self.request.GET.get('article_slug')
        article = Article.objects.get(slug=article_slug)
        current_user = UserAccount.objects.get(user=request.user)
        current_user.fav_articles.remove(article)
        current_user.save()
        return JsonResponse({ 'ok':'ok' })

class SearchView(View):
    template_name = 'search.html'

    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('q')
        categories = Category.objects.all()
        found_articles = Article.objects.filter(
            Q(title__icontains=query)|
            Q(content__icontains=query))
        context = {
            'found_articles': found_articles,
            'categories': categories
        }
        return render(self.request, self.template_name, context)

mp_project/mediaportalapp/templates/article_detail.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container mt-4" style="min-height: 100vh">
    <h1 class="text-center">{{ article.title }}</h1>
    <hr/>
    <p><img src="{{ article.image.url }}" style="width: 60%"></p>
    <div class="container">
        <div class="col-sm-12 mb-2">
            <div class="col-sm-7 offset-sm-2">
                {{ article.content|safe }}
                <hr/>
                <h4>Понравилась статья?</h4>
                {% if not request.user.is_authenticated %}
                <h6>Оценивать статьи могут только зарегистрированные пользователи!</h6>
                <p>Пожалуйста, <a href="{% url 'login' %}">войдите</a>, или <a href="{% url 'registration' %}">зарегистрируйтесь</a>, 
                    чтобы получить возможность оценивать статьи, добавлять их в избранное и писать комментарии.</p>
                {% else %}
                <a href="#" id="like"><i class="fa fa-thumbs-o-up" style="color: green"></i></a>
                <span id="liked">{{ article.likes }}</span>
                <a href="#" id="dislike" class="ml-2"><i class="fa fa-thumbs-o-down" style="color: red"></i></a>
                <span id="disliked">{{ article.dislikes }}</span>
                <hr/>
                <p class="add_to_fav_{{ article.slug }}">
                    {% if article in current_user.fav_articles.all %}
                        <a href="#" class="article_remove" data-slug="{{ article.slug }}">
                            <button class="btn btn-default disabled">Добавлено в избранное</button>
                        </a>
                    {% else %}
                        <a href="#" class="article_add" data-slug="{{ article.slug }}">
                            <button class="btn btn-danger">Добавить в избранное</button>
                        </a>
                    {% endif %}
                {% endif %}
                </p>
                <p class="article_added_{{ article.slug }}"></p>
                <h2>Комментарии:</h2>
                {% for comment in article_comments %}
                <div class="col-sm-12">
                    <hr/>
                    <small>{{ comment.author.username }}</small>
                    <p>{{ comment.comment }}</p>
                    <small>{{ comment.timestamp|date:'Y-m-d' }}</small>
                </div>
                {% empty %}
                <strong class="empty">К данной статье еще нет комментариев :(</strong>
                {% endfor %}
                <div class="col-sm-12 new_comment">
                </div>
                <hr/>
            </div>
            {% if request.user.is_authenticated %}
            <div class="col-sm-7 offset-sm-2 mb-4">
                <form action="" method="POST">
                    <input type="hidden" id="article" data-id="{{ article.id }}">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" value="Добавить комментарий" id="add_comment" data-toggle="modal" data-target=".bs-example-modal-sm">
                </form>
            </div>
            {% endif %}
        </div>
    </div>
</div>    
{% endblock content %}

{% block jquery %}
<script>
    $(document).ready(function(){
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');
        $('#add_comment').on('click', function(e){
            e.preventDefault()
            var article_id = $('#article').attr('data-id')
            var comment = $('#id_comment').val()
            data = {
                article_id: article_id,
                comment: comment,
                csrfmiddlewaretoken: csrftoken
            }
            $.ajax({
                type: "POST",
                url: "{% url 'add_comment' %}",
                dataType: "json",
                data: data,
                success: function(data){
                    $.each(data, function(field){
                        $('.new_comment').prepend('<hr/><small>'+data[field]['author']+'</small><p>'+
                        data[field]['comment']+'</p><small>'+data[field]['timestamp']+'</small>')
                        $('#id_comment').val('')
                        $('.empty').html('')
                    })
                }
            })
        })
    })
</script>
<script>
    $(document).ready(function(){
        $('#like').on('click', function(e){
            e.preventDefault()
            let like = 'like'
            let article_id = $('#article').attr('data-id')
            data = {
                article_id: article_id,
                like: like
            }
            $.ajax({
                type: "GET",
                url: '{% url "user_reaction" %}',
                dataType: 'json',
                data: data,
                success: function(data){
                    $('#liked').html(data.likes)
                    $('#disliked').html(data.dislikes)
                }
            })
        })
    })
    $(document).ready(function(){
        $('#dislike').on('click', function(e){
            e.preventDefault()
            let dislike = 'dislike'
            let article_id = $('#article').attr('data-id')
            data = {
                article_id: article_id,
                dislike: dislike
            }
            $.ajax({
                type: "GET",
                url: '{% url "user_reaction" %}',
                dataType: 'json',
                data: data,
                success: function(data){
                    $('#liked').html(data.likes)
                    $('#disliked').html(data.dislikes)
                }
            })
        })
    })
</script>
<script>
    $(document).ready(function(){
        $('.article_add').on('click', function(e){
            e.preventDefault()
            let article_slug = $(this).attr('data-slug')
            data = {
                article_slug: article_slug
            }
            $.ajax({
                type: "GET",
                url: "{% url 'add_to_fav' %}",
                dataType: 'json',
                data: data,
                success: function(data){
                    $('.article_added_'+article_slug).html('<a href="#" class="article_remove" data-slug="'+article.slug+
                    '"><button class="btn btn-default disabled">Добавлено в избранное</button></a>')
                    $('.add_to_fav_'+article_slug).css('display', 'none')
                }
            })
        })
    })
</script>
{% endblock jquery %}

mp_project/mediaportalapp/templates/category_detail.html
{% extends "index.html" %}

{% block content %}
    <div class="container mt-4" style="min-height: 100vh">
        <h2>Статьи из категории: {{ category.name }}</h2>
        <hr/>
        <div class="row">
            {% for article in articles_from_category %}
            <div class="col-sm-12 d-flex mb-4">
            <div class="col-sm-4">
                <img src="{{ article.image.url }}" alt="#" class="img-fluid"/>
            </div>
            <div class="col-sm-8">
                <h2>{{ article.title }}</h2>
                <p>{{ article.content|truncatewords:15 }}</p>
                <a href="{{ article.get_absolute_url }}"><button class="btn btn-primary">Читать</button></a>
            </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

mp_project/mediaportalapp/templates/login.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container" style="min-height: 100vh">
    <h3 class="mt-4 text-center">Авторизация пользователя</h3>
    <hr/>
    <div class="row">
        <div class="col-sm-6 offset-sm-3 mb-4">
            <form action="" method="post">
                {{ form.error }}
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Войти">
            </form>
        </div>
    </div>
</div>
{% endblock content %}

mp_project/mediaportalapp/templates/registration.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container" style="min-height: 100vh">
    <h3 class="mt-4 text-center">Регистрация нового пользователя</h3>
    <hr/>
    <div class="row">
        <div class="col-sm-6 offset-sm-3 mb-4">
            <form action="" method="post">
                {{ form.error }}
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Зарегистрироваться">
            </form>
        </div>
    </div>
</div>
{% endblock content %}

mp_project/mediaportalapp/templates/search.html
{% extends "index.html" %}

{% block content %}
<div class="container mt-4" style="min-height: 100vh">
    <div class="row">
        <div class="col-sm-12">
            <h3 class="mt-2">Результаты поиска: {{ found_articles.count }}</h3>
            {% for article in found_articles %}
            <a href="{{ article.get_absolute_url }}"><h4>{{ article.title }}</h4></a>
            <p>{{ article.content|truncatewords:30 }}</p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

mp_project/mediaportalapp/templates/user_account.html
{% extends "index.html" %}

{% block content %}

<div class="container" style="min-height: 100vh">
    <h3 class="text-center mt-3">Личная информация пользователя {{ current_user.user }}</h3>
    <hr>
    <div class="row">
        <div class="col-sm-4">
            <h4>Личная информация</h4>
            <p>Логин: {{ current_user.user }}</p>
            <p>Имя: {{ current_user.first_name }}</p>
            <p>Фамилия: {{ current_user.last_name }}</p>
            <p>E-mail: {{ current_user.email }}</p>
        </div>
        <div class="col-sm-8">
            <h4 class="text-center"><strong>Избранные статьи</strong></h4>
            <ul class="button-group">
                {% for article in current_user.fav_articles.all %}
                <li class="list-group-item list_{{ article.slug }}">
                    <div class="d-flex justify-content-between align-items-center">
                        <a href="{{ article.get_absolute_url }}" style="text-decoration: none" class="text-dark">{{ article.title }}</a>
                        <a class="article_remove" data-slug="{{ article.slug }}" href=""><button class="btn btn-danger">Удалить</button></a>        
                    </div>
                </li>
                {% endfor %}
            </ul>        
        </div>
    </div>
</div>

{% endblock content %}

{% block jquery %}
<script>
    $(document).ready(function(){
        $('.article_remove').on('click', function(e){
            e.preventDefault()
            let article_slug = $(this).attr('data-slug')
            data = {
                article_slug: article_slug
            }
            $.ajax({
                type: "GET",
                url: "{% url 'remove_from_fav' %}",
                dataType: 'json',
                data: data,
                success: function(data){
                    $('.list_'+article_slug).css('display', 'none')
                }
            })
        })
    }) 
    
</script>
{% endblock jquery %}